# Site settings
title: Harrison 
header-img: img/home-bg.png
email: harrisontran@outlook.com
copyright_name: lambigini87
description: > # this means to ignore newlines until "baseurl:"
  Tran
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  lambigini87
learn_profile: lambigini87
email_username: harrisontran@outlook.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
